spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helmesdb
    username: postgres
    password: postgres

    initialization-mode: always


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect